### ISSUE TITLE
chore: fix few code-style issues

### ISSUE THREAD

**Issue by andela-anandaa** [AndelaOSP/maintt-frontend#5]
See issues raised by [Codacy here](https://www.codacy.com/app/AndelaOSP/maintt-frontend/issues?bid=3853699&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ==)

**Comment by nyambati** [comment]
I will work on this, Although some of the file like `index.js` the `console.log()` is unvoidable, you should probably ignore this file.
